# Generated by Django 4.2.30 on 2026-06-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='icon_bg',
            field=models.CharField(default='#1a1a2e', max_length=200),
        ),
    ]
